Add system test of 'buildah help' with a tiny fix
containers/buildah pull request #3151
Opened 2021-04-15 21:39 UTC by hshiina

Signed-off-by: Hironori Shiina <shiina.hironori@jp.fujitsu.com>

#### What type of PR is this?

/kind other

#### What this PR does / why we need it:
Add a system test of `buildah help` copying a system test of `podman help`.

Also remove an unexpected empty line from the usage template of commands.

#### How to verify it
Run the added system test:

~~~
$ bats tests/help.bats
~~~

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
None
```

2021-04-15 22:45 UTC, TomSweeneyRedHat commented
@edsantiago PTAL.  I thought we did something like this elsewhere?
Also the conformance test is not at all happy.

2021-04-16 08:10 UTC, rhatdan commented
@hshiina Does this do any more then ./hack/xref-helpmsgs-manpages?

2021-04-16 13:09 UTC, edsantiago commented
This is a copy-paste of the same [podman test](https://github.com/containers/podman/blob/35b62ef19f307fb365eb7a8734e456160f7b22a8/test/system/015-help.bats) with a lot of code removed; some because it's not applicable (`-l`), some for reasons I haven't looked into (possibly because the buildah help messages don't conform to the same rules as podman?).

I won't have time to review until Monday, but on first glance I'm almost totally OK with this (there's a "podman" in a `die` message that should be changed). At this time it doesn't do much more than the `xref` script, but I believe @hshiina is intending to extend that in future work; and this could give us important bug catches such as those the podman test does (usually SEGVs when invoking with wrong number of args). Plus, `xref` doesn't run in gating-test context.

2021-04-17 02:06 UTC, hshiina commented
I focused on system tests and overlooked `./hack/xref-helpmsgs-manpages`.
As @edsantiago mentions, this test does no more things than the script.
This test may not be necessary because `help` doesn't require system tests where `buildah` works with other components such as an OCI runtime.

2021-04-19 15:53 UTC, edsantiago requested changes
@hshiina this is good work, and it does perform tests that are not present in `hack/xref-helpmsgs-manpages`. I think buildah would benefit from including this in CI. One trivial correction, and I will gladly merge this after that's fixed. Thank you!

2021-04-19 15:53 UTC, edsantiago commented on tests/help.bats
> +        die "Internal error: no commands found in 'podman help $@' list"
`s/podman/buildah/`

2021-04-19 20:34 UTC, edsantiago commented
LGTM but could you please squash your commits? The typo fix doesn't merit a separate commit. Thank you!

2021-04-20 20:27 UTC, edsantiago commented
/approve
/lgtm

Thank you @hshiina !

2021-04-20 20:27 UTC, edsantiago approved these changes

2021-04-21 10:02 UTC, merged