Set user namespace defaults correctly for the library
containers/buildah pull request #4130
Opened 2022-07-21 22:00 UTC by nalind

#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Set the default for user namespaces correctly for callers that don't use our CLI, e.g. OpenShift or our own tutorials.  When we don't do that, commands invoked through RUN instructions can see weird things, in this case an empty /sys/fs/cgroup directory.

#### How to verify it

New integration test!

#### Which issue(s) this PR fixes:

This caused test failures in https://github.com/openshift/builder/pull/304 before it started explicitly specifying a user namespace setting to work around it, but it's not the only consumer that might be affected.

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
None
```

2022-07-21 22:22 UTC, TomSweeneyRedHat commented
Lint isn't happy @nalind, otherwise LGTM

2022-07-22 03:28 UTC, flouthoc commented on tests/tutorial/tutorial.go
> +	defer buildStore.Shutdown(false)
I think `err` for `) Shutdown(` needs to be checked in order to make linter happy.

2022-07-22 03:28 UTC, flouthoc requested changes
LGTM other than one issue above

2022-07-22 14:09 UTC, flouthoc commented
Failing conformance is a networking flake restarted.

2022-07-22 15:20 UTC, nalind commented
Added an error check, fixed a typo in a comment.

2022-07-22 18:18 UTC, flouthoc approved these changes
LGTM
/lgtm

2022-07-22 18:22 UTC, merged

2022-07-22 20:40 UTC, edsantiago commented
@lsm5 this is going to need specfile changes:
- easy and recommended IMHO: at install time, `rm .../tutorial.bats`
- hard: build and package the new `tutorial` binary, and make all sorts of changes to gating tests

@nalind do you have any objection to going the easy route? Are the tutorial tests necessary for confidence in Fedora or RHEL environments?

2022-07-22 21:21 UTC, nalind commented
This specific bug was caught in OpenShift CI, but openshift/builder only updates to a new version of buildah when someone manually opens a PR, so I don't currently have a clear picture of exactly where between v1.24.2 and v1.26.2 it was that we broke this.  So, in a sense, we already test this case on RHEL, but the feedback is not always timely.
How difficult is the hard route that we're talking about?

2022-07-22 23:28 UTC, edsantiago commented
> How difficult is the hard route that we're talking about?

Not really difficult, just complicated: lots of little steps that need to be coordinated in sequence. (That's assuming that it's like the two last helper-binary additions. If there's anything additional, YMMV). I will look into it on Monday. @lsm5, and Jindrich who I can't tag on github: we will all need to coordinate this together. But again, next week.

Thanks @nalind for your fair response.

2022-08-08 11:36 UTC, jnovy commented
Just added the buildah-tutorial binary to buildah-tests: https://gitlab.com/redhat/centos-stream/rpms/buildah/-/merge_requests/136

2022-08-08 11:43 UTC, edsantiago commented
Thank you @jnovy. @lsm5 can we assume that the same has been done on Fedora?