test: warning behaviour for unset/set `TARGETOS`,`TARGETARCH`,`TARGETPLATFORM` or `TARGETVARIANT`
containers/buildah pull request #4310
Opened 2022-10-01 07:15 UTC by flouthoc

Test buildah's warning behaviors for unset or set `TARGETOS`, `TARGETARCH`, `TARGETPLATFORM` or `TARGETVARIANT` args when set or unset directly or indirectly by the user.

Adds missing test for: https://github.com/containers/buildah/pull/4295

2022-10-01 07:16 UTC, flouthoc commented
@lucacome @rhatdan @nalind @containers/buildah-maintainers PTAL

2022-10-01 09:51 UTC, rhatdan commented
LGTM
@edsantiago PTAL

2022-10-03 11:38 UTC, edsantiago requested changes
Don't merge yet please, I have a few concerns. Am looking into ways to confirm and address.

2022-10-03 12:30 UTC, edsantiago requested changes
Here's a shorter, cleaner version that uses only one containerfile for all tests, and is more careful about checking for warnings:
```bash
@test "build test warning for preconfigured TARGETARCH, TARGETOS, TARGETPLATFORM or TARGETVARIANT" {
  _prefetch alpine
  containerfile=${TEST_SCRATCH_DIR}/Containerfile

  # buildah should not warn when any of these is indirectly set by cli options
  local -a checkvars=(ARCH OS PLATFORM VARIANT)
  echo "FROM alpine" >$containerfile
  for var in "${checkvars[@]}"; do
    echo "ARG TARGET${var}" >>$containerfile
  done
  echo "COPY . ." >>$containerfile

  # With explicit and full --platform, there should be no warnings
  run_buildah build $WITH_POLICY_JSON --platform linux/amd64/v2 -t source -f $containerfile
  assert "$output" !~ "missing .* build argument" \
         "With explicit --platform, buildah should not warn"

  # Without --platform, we want one warning for each variable
  run_buildah build $WITH_POLICY_JSON -t source -f $containerfile
#  for var in "${checkvars[@]}"; do
  for i in $(seq 0 3); do
    var="TARGET${checkvars[$i]}"
    # The '..'s cover backslash-quote: "missing \"TARGETFOO\" ..."
    assert "${lines[$i]}" =~ "missing ..${var}.. build argument" \
           "buildah should warn about undefined ${var}"
  done
}
```
Incidentally, is `--os linux` or `--os linux/amd64` supposed to shutup the `missing TARGETOS` warning? Because it doesn't. I gave up trying to add tests for that.

2022-10-03 12:30 UTC, edsantiago commented on tests/bud.bats
> +  cat > ${TEST_SCRATCH_DIR}/bud/platform/Dockerfile << _EOF
A lot of duplication

2022-10-03 12:30 UTC, edsantiago commented on tests/bud.bats
> +  assert "$output" !~ "--build-arg TARGETARCH"
Too explicit. It's much better to have a looser test here, such that any warning will cause a test failure.

2022-10-03 12:30 UTC, edsantiago commented on tests/bud.bats
> +  expect_output --substring "build-arg TARGETVARIANT"
lots of duplication

2022-10-04 04:40 UTC, flouthoc commented
Thanks @edsantiago for the patch.

> Incidentally, is --os linux or --os linux/amd64 supposed to shutup the missing TARGETOS warning? Because it doesn't. I gave up trying to add tests for that.

`--os` doesn't do but `--platform` does, I think `--os` needs to be fixed, I'll open a new PR fixing `--os` and will also amend the test then.

2022-10-04 11:36 UTC, edsantiago commented
Thank you!

/lgtm

2022-10-04 11:36 UTC, edsantiago approved these changes

2022-10-04 11:42 UTC, merged