`CONTRIBUTING.md`: Update contact information
containers/buildah pull request #4313
Opened 2022-10-03 20:00 UTC by AndASM

#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:
`CONTRIBUTING.md` is outdated. New contributors will be directed to a dead freenode channel.

Changes:
- Freenode is no longer used, IRC has moved to [libera.chat](https://libera.chat).
- \[matrix\] is federated into the `#podman` channel and can be used instead of IRC.

#### How to verify it
Read `CONTRIBUTING.md`.

#### Which issue(s) this PR fixes:

Fixes #4308

#### Special notes for your reviewer:
I am assuming this counts as "developer-facing" not "user-facing" so I have put `None` under the release notes. Is that correct?

#### Does this PR introduce a user-facing change?

```release-note
None
```

2022-10-04 10:05 UTC, rhatdan commented
LGTM
@TomSweeneyRedHat PTAL

2022-10-04 20:37 UTC, TomSweeneyRedHat commented on CONTRIBUTING.md
> +Alternatively [\[matrix\]](https://matrix.org) can be used to access the same channel via federiation at https://matrix.to/#/#podman:chat.fedoraproject.org.
I'm 99% sure it should be federation and not federation.

```suggestion
Alternatively, [\[matrix\]](https://matrix.org) can be used to access the same channel via federation at https://matrix.to/#/#podman:chat.fedoraproject.org.
```

2022-10-04 20:38 UTC, TomSweeneyRedHat commented on CONTRIBUTING.md
> +_This list sees low traffic, the GitHub links or IRC above are better options in most cases._
```suggestion
```

2022-10-04 20:39 UTC, TomSweeneyRedHat commented on CONTRIBUTING.md
>  You can also use the github
I know it's old, but please touch up
```suggestion
You can also use GitHub
```

2022-10-04 20:41 UTC, TomSweeneyRedHat commented on CONTRIBUTING.md
>  You can also use the github
Also, please add:
`[Discussions](https://github.com/containers/podman/discussions),`

2022-10-17 12:51 UTC, rhatdan commented
@AndASM Are you still working on this, or would you rather us finish it?

2022-10-18 02:39 UTC, AndASM commented
> @AndASM Are you still working on this, or would you rather us finish it?

Sorry about that, I missed the update emails and have been distracted and busy lately. I'll try to take a look tomorrow if you haven't otherwise taken care of it.

2022-10-18 03:32 UTC, flouthoc requested changes
Could you reduce length of your commit title please ?

2022-10-18 03:34 UTC, flouthoc commented
Oops it was commit  2c06b50cf1635f1504bf83a19fb414a6f8bc99c5 caused by using github rebase , @AndASM Could you squash commits into one ?

2022-11-01 13:39 UTC, rhatdan commented
@AndASM Are you still working on this one?

2022-12-02 10:47 UTC, closed without merging

2022-12-02 21:14 UTC, AndASM commented
Oops, sorry about that! Life has been a bit crazy of late.

I squashed the commits into one, and rebased it on the current main branch. Is this still okay to pull? It might help someone to have those updates to the documentation. @rhatdan?

2022-12-04 22:33 UTC, rhatdan commented
I can't seem to reopen, could you open a new PR with just one commit.