Makefile: Fix install on FreeBSD
containers/buildah pull request #4365
Opened 2022-10-21 07:41 UTC by dfr

The '-D' option to install differs between Linux and FreeBSD. On Linux, it creates missing directories but on FreeBSD, it removes a destdir prefix from an optional 'metalog'. This makes the directory creation explicit using 'install -d'.

Signed-off-by: Doug Rabson <dfr@rabson.org>

#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

It allows installing buildah into an empty DESTDIR directory. I missed this problem because on my test machines, I was typically installing to /usr/local/bin which nearly always exists. The use of '-D' also had the side effect of suppressing the following '-m0755' argument since '-D' takes an argument; install's default mode is 0755 so the file was installed with the correct mode by accident.

#### How to verify it

```
$ d=$(mktemp -d)
$ sudo gmake DESTDIR=$d install
install -d -m 755 /tmp/tmp.KewiGMuZ//usr/local/bin
install -m 755 bin/buildah /tmp/tmp.KewiGMuZ//usr/local/bin/buildah
gmake -C docs install
gmake[1]: Entering directory '/home/dfr/go/src/github.com/containers/buildah/docs'
install -d /tmp/tmp.KewiGMuZ//usr/local/share/man/man1
install -m 0644 buildah*.1 /tmp/tmp.KewiGMuZ//usr/local/share/man/man1
install -m 0644 links/buildah*.1 /tmp/tmp.KewiGMuZ//usr/local/share/man/man1
gmake[1]: Leaving directory '/home/dfr/go/src/github.com/containers/buildah/docs'
$ sudo rm -rf $d
```

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
None
```

2022-10-21 08:11 UTC, flouthoc requested changes
@dfr PR LGTM but commit needs `[NO NEW TESTS NEEDED]`

2022-10-21 08:53 UTC, flouthoc approved these changes
LGTM

2022-10-23 10:29 UTC, dfr commented
I added a second commit to fix the install.tools rule on FreeBSD

2022-10-23 14:28 UTC, flouthoc approved these changes
LGTM
@nalind @rhatdan PTAL

2022-10-24 14:09 UTC, rhatdan commented
/lgtm

2022-10-24 14:13 UTC, merged