fix(sec): upgrade gopkg.in/yaml.v3 to 3.0.0
containers/buildah pull request #4651
Opened 2023-03-09 11:58 UTC by chncaption

### What happened？
There are 1 security vulnerabilities found in gopkg.in/yaml.v3 v3.0.0-20200313102051-9f266ea9e77c
- [CVE-2022-28948](https://www.oscs1024.com/hd/CVE-2022-28948)

### What did I do？
Upgrade gopkg.in/yaml.v3 from v3.0.0-20200313102051-9f266ea9e77c to 3.0.0 for vulnerability fix

### What did you expect to happen？
Ideally, no insecure libs should be used.

### The specification of the pull request
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS

2023-03-09 15:52 UTC, rhatdan commented
@chncaption you need to sign your commit.

git commit -a --amend -s
git push --force

2023-03-17 20:05 UTC, mtrmac requested changes
- This is in `tools`, a part of the linter, it shouldn’t show up in the product anyway.
- We can’t reasonably modify vendored code this way.

2023-03-17 20:12 UTC, mtrmac commented
This should (eventually? now?) be fixed by just updating the linter, instead.

2023-03-17 21:24 UTC, mtrmac commented
Actually, we are _already_ using a more recent version: https://github.com/containers/buildah/blob/f694eca9cd885bb38518b121534cf11c8e11be4a/tests/tools/vendor/modules.txt#L601 .

So this PR seems to be an outcome of a misunderstanding of the details of how vendoring, and/or how to detect which version is used — or, quite likely, the consequence of an incorrectly implemented vulnerability scanning tool.

2023-03-17 21:24 UTC, closed without merging