Fix an overflow on retries on container name conflicts
containers/buildah pull request #4752
Opened 2023-04-22 00:34 UTC by mtrmac

#### What type of PR is this?

> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### What this PR does / why we need it:

Original report https://github.com/containers/buildah/issues/4679 , probably requires a deterministically-seeded RNG.

Because Go integers silently overflow, and 10 is multiple of 2, repeatedly multiplying by 2 eventually turns suffixDigitsModulo
into all-bits-zero, triggering a division by zero.

So, cap the suffix to a 9-digit one. That is very likely to be sufficient.

(But don't actually limit the number of retries. We could do that as well, for extra robustness. OTOH that would be another bit of code that we don't test...)

#### How to verify it

With a deterministic RNG, and 32-bit integers, about 30 repeated triggers of this code should trigger that overflow. I didn’t try.

#### Which issue(s) this PR fixes:

Fixes #4679 

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
None
```

2023-04-22 04:14 UTC, flouthoc requested changes
@mtrmac Does this needs a test ? or if not possible you can add `NO NEW TESTS NEEDED` in commit

2023-04-22 11:57 UTC, rhatdan commented
LGTM

2023-04-24 15:21 UTC, mtrmac commented
> you can add `NO NEW TESTS NEEDED` in commit

Did that, with an attempt at a justification in the commit. I can very well see an argument that this should have a unit test anyway, say so if you want me to write one.

2023-04-28 21:13 UTC, TomSweeneyRedHat commented
LGTM
Test seemed to be timing out pulling Alpine.  I've restarted.

2023-05-02 22:08 UTC, TomSweeneyRedHat commented
Happy green test buttons.  @rhatdan @flouthoc @nalind PTAL

2023-05-02 23:20 UTC, rhatdan commented
/approve
/lgtm

2023-05-02 23:20 UTC, merged