Ensure created ImageSource / ImageDestination objects are closed
containers/buildah pull request #4945
Opened 2023-07-31 15:57 UTC by mtrmac

#### What type of PR is this?

> /kind bug

#### What this PR does / why we need it:

The `ImageSource`/`ImageDestination` API requires `.Close()` to be called to clean up resources. In some cases that matters, in others it's a matter of principle / ability to change the underlying implementation without adverse effects.

#### How to verify it

Existing CI for functionality. I guess code inspection for correctness and not missing anything

#### Which issue(s) this PR fixes:

Fixes #4894

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
None
```

2023-07-31 17:44 UTC, flouthoc requested changes
LGTM

@mtrmac `[NO NEW TESTS NEEDED]` in commits.

2023-07-31 18:43 UTC, mtrmac commented
This is motivated by #4894 .

The history is that we once had a Buildah(IIRC) test timeout triggering a panic dump, which showed _hundreds_ of HTTP goroutines, suggesting something somewhere isn’t closing HTTP connections, or persistent HTTP clients. That caused me to look for users of `NewImage{Source,Destination}` missing a `Close` (though I have no evidence that that was the origin of those goroutines).

2023-07-31 19:42 UTC, rhatdan commented
/lgtm
/hold

2023-08-01 07:06 UTC, vrothberg approved these changes
LGTM
/hold cancel

2023-08-01 07:11 UTC, merged