Fix caching when mounting a cached stage with COPY/ADD
containers/buildah pull request #5445
Opened 2024-03-31 04:59 UTC by aaronlehmann

#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

A comment states that `avoidLookingCache` is set when a previous stage that executed as part of the build is referenced by `--mount`, to avoid reusing content from an older build of the stage:

    // Only attempt to find cache if its needed, this part
    // so that if a step is using RUN --mount and mounts
    // previous stages then it uses the freshly built stage
    // of re-using the older stage from the store.

However, stages consisting of `COPY`/`ADD` seem to be flagged with `didExecute` even if they were fetched from cache instead. I believe this is an oversight, and these stages should not prevent subsequent caching.

Also, `avoidLookingCache` would prevent a cache push, but I think it should only prevent cache lookups, since populating the cache is still useful in these caess.

#### How to verify it

Run the provided test case.

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

It's very possible I'm misunderstanding something, but I believe the `RUN` step in test case I've added wrongly skips cache, and I'd appreciate some pointers in the right direction if what I've proposed here isn't the right solution.

#### Does this PR introduce a user-facing change?

None

2024-03-31 10:03 UTC, rhatdan commented
/approve
LGTM
@nalind @flouthoc PTAL

2024-03-31 10:03 UTC, rhatdan commented
Thanks @aaronlehmann

2024-03-31 16:48 UTC, flouthoc requested changes
@aaronlehmann Thanks for PR, could you fill the section of `issue` in PR description with a small reproduce so its easier to verify. As of now I'm unable to exactly understand what was the problem before this PR.

2024-03-31 18:03 UTC, aaronlehmann commented
@flouthoc: I added some notes in the "Issue" section. Please let me know if I can clarify further.

2024-04-02 19:34 UTC, flouthoc approved these changes
@aaronlehmann Thanks PR LGTM, could you please rebase it :)

2024-04-02 19:58 UTC, aaronlehmann commented
Thanks! Rebased.

2024-04-02 21:13 UTC, rhatdan commented
/lgtm
/hold

2024-04-03 11:54 UTC, rhatdan commented
/unhold

2024-04-03 11:58 UTC, merged