build, run: record hash or digest in image history for sources used in `--mount`
containers/buildah pull request #5691
Opened 2024-08-18 17:00 UTC by flouthoc

When using `--mount=type=bind` or `--mount=type=cache` the hash or digest of source in these flags should be added to image history so buildah can burst cache if files on host or image which is being used as source is changed.

Closes
* https://github.com/containers/podman/issues/23382
* https://github.com/containers/buildah/issues/5400

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### What this PR does / why we need it:

#### How to verify it

#### Which issue(s) this PR fixes:

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
build, run: record hash or digest in image history for sources used in `--mount`
```

2024-08-18 17:01 UTC, flouthoc commented
Need to add tests, will undraft then.

2024-08-18 23:58 UTC, flouthoc commented
Will rebase after this https://github.com/containers/buildah/pull/5693

2024-09-17 17:52 UTC, nalind commented
I'm surprised that we'd care about the contents of caches.  I'd be inclined to archive the contents of a directory (and create a single-entry archive for a non-directory) to account for different permissions/ownership/datestamps/xattrs and to safely handle soft and hard links.

2024-09-17 18:49 UTC, flouthoc commented
> I'm surprised that we'd care about the contents of caches. I'd be inclined to archive the contents of a directory (and create a single-entry archive for a non-directory)

If i'm understanding this correctly, did you mean instead of `computeDirectoryHash` or `computeFileHash` separately and recursively I should just create a temporary archive of the context dir and write its hash in history ? And on everyrun I can do the same process again to check if hash is matching with what is written in the `history` ?  The idea sounds good to me.

2024-09-17 19:10 UTC, nalind commented
> > I'm surprised that we'd care about the contents of caches. I'd be inclined to archive the contents of a directory (and create a single-entry archive for a non-directory)
> 
> If i'm understanding this correctly, did you mean instead of `computeDirectoryHash` or `computeFileHash` separately and recursively I should just create a temporary archive of the context dir and write its hash in history?

I wouldn't expect the archive to be written anywhere, but the digest of an archive is something we already use as a way of describing contents, when handling COPY and ADD instructions.  I don't know yet about doing this over the entire build context or additional build context if only a portion of it is being used at that point (i.e., if "src" is set to a subdirectory).

2024-09-17 19:57 UTC, flouthoc commented
> > > I'm surprised that we'd care about the contents of caches. I'd be inclined to archive the contents of a directory (and create a single-entry archive for a non-directory)
> > 
> > 
> > If i'm understanding this correctly, did you mean instead of `computeDirectoryHash` or `computeFileHash` separately and recursively I should just create a temporary archive of the context dir and write its hash in history?
> 
> I wouldn't expect the archive to be written anywhere, but the digest of an archive is something we already use as a way of describing contents, when handling COPY and ADD instructions. I don't know yet about doing this over the entire build context or additional build context if only a portion of it is being used at that point (i.e., if "src" is set to a subdirectory).

This sounds good to me, i will amend the PR.

2024-10-03 10:49 UTC, sanmai-NL commented
@flouthoc

I'm seeing this behavior with `podman build`, will this be fixed by this change too?

```Containerfile
ARG PATH_1=mydirectory
ARG SELINUXRELABEL=,z
ARG DISTRO=PATH_1
RUN --mount=type=bind,source=${PATH_1:?},target=/tmp/${PATH_1:?}${SELINUXRELABEL:?} \
  echo Nop
```

Subsequently, `/tmp/mydirectory` ends up in an image layer rather than being ephemeral and only mounted at build time. This bloats the image and leaks information.

2024-10-03 17:14 UTC, flouthoc commented
> ```dockerfile
> RUN --mount=type=bind,source=${PATH_1:?},target=/tmp/${PATH_1:?}${SELINUXRELABEL:?}
> ```

@sanmai-NL Are contents of `PATH_1` ending up in your final built image as well ? A layer is created so that i can be used later but I don't think contents of `RUN --mount` are part of your image.

2024-10-04 06:50 UTC, sanmai-NL commented
Thanks for your response. Yes indeed, they do end up in there, which I find surprising. And which is the reason for my comment.

Some factors which may cause this in case the problem isn't general. This happens when running `podman build` from a containerized Podman. Maybe ID mapping also causes some sort if copy operation instead of a bind mount.

2024-10-04 06:52 UTC, sanmai-NL commented
> > ```dockerfile
> 
> > RUN --mount=type=bind,source=${PATH_1:?},target=/tmp/${PATH_1:?}${SELINUXRELABEL:?}
> 
> > ```
> 
> 
> 
> @sanmai-NL Are contents of `PATH_1` ending up in your final built image as well ? A layer is created so that i can be used later but I don't think contents of `RUN --mount` are part of your image.

Re-reading your comment... So you do find this ending up in a layer by-design, do you? But this way, information leaks and the image bloats.

2024-10-10 04:26 UTC, flouthoc commented
> > > 
> > 
> > 
> > > RUN --mount=type=bind,source=${PATH_1:?},target=/tmp/${PATH_1:?}${SELINUXRELABEL:?}
> > 
> > 
> > > 
> > 
> > 
> > @sanmai-NL Are contents of `PATH_1` ending up in your final built image as well ? A layer is created so that i can be used later but I don't think contents of `RUN --mount` are part of your image.
> 
> Re-reading your comment... So you do find this ending up in a layer by-design, do you? But this way, information leaks and the image bloats.

@sanmai-NL What you are describing is a different bug, would it be possible to create a small reproducer and open a new issue ?

2024-12-18 13:23 UTC, flouthoc commented
Since https://github.com/containers/buildah/pull/5693 is merged, i'll get back to this.

2025-01-14 22:03 UTC, flouthoc commented
@nalind @containers/buildah-maintainers PTAL

2025-01-14 22:34 UTC, nalind commented on internal/parse/parse.go
> +		}
There's no check here that `option` includes a "=" character, so it's possible there's a crash here.

2025-01-14 22:34 UTC, nalind commented on internal/util/util.go
> +	defer tarWriter.Close()
In the general case, the tar writer would need to be closed before the digest is read back, so that the digest calculation wouldn't miss the end-of-archive marker.

2025-01-14 22:34 UTC, nalind commented on internal/util/util.go
> +		header.Name = filepath.ToSlash(path)
I think that this is going to need to be computed to be relative to the top-level directory.

2025-01-15 18:39 UTC, flouthoc commented
@nalind Could you PTAL again.

2025-01-15 21:24 UTC, nalind requested changes
Be _very_ sure you want to use sha256 over an entire directory tree.  It can be an expensive computation if the tree is large.

2025-01-15 21:24 UTC, nalind commented on imagebuildah/stage_executor.go
> +				return "", nil, false, err
Get in the habit of adding context to errors being passed up from calls to methods that returned them, to make it easier to follow the call stack when troubleshooting and debugging.  Not just here, but throughout this PR.

2025-01-15 21:24 UTC, nalind commented on imagebuildah/stage_executor.go
> +							return "", fmt.Errorf("Unable to generate checksum for image history: %w", err)
Text passed to fmt.Errorf() is context, not a full error message, so it should not be capitalized, and should merely describe what was being attempted, so that the caller can add more context if it wishes.  "generating checksum for directory %q in %q: %w" would be enough here, since the caller will prepend context of its own.  Not just here, but throughout this PR.

2025-01-15 21:24 UTC, nalind commented on internal/util/util.go
> +		header, err := tar.FileInfoHeader(info, info.Name())
The second argument being passed to `FileInfoHeader()` is not correct.

2025-01-15 21:24 UTC, nalind commented on imagebuildah/stage_executor.go
> +		}
This looks like it will only consider the last `--mount` flag, and ignore the rest if there are more than one.

2025-01-15 21:24 UTC, nalind commented on internal/util/util.go
> +func GeneratePathChecksum(sourcePath string) (string, error) {
This can be a helper function in the package that calls it until we find that we actually need to call it from somewhere else as well.  It might benefit from a unit test.

2025-01-15 21:24 UTC, nalind commented on internal/parse/parse.go
> +func GetFromAndSourceKeysFromMountFlag(mount string) (string, string) {
This can be a helper function in the package that calls it until we find that we actually need to call it from somewhere else as well.

2025-01-15 21:24 UTC, nalind commented on internal/util/util.go
> +	tarWriter.Close()
Move this to just above the `if err != nil` check, if its return value isn't going to be checked.

2025-01-16 00:38 UTC, sanmai-NL commented
https://github.com/BLAKE3-team/BLAKE3

2025-01-16 19:09 UTC, nalind commented
In its current form, this considers caches where a "src" option is used to select a subdirectory, but not otherwise.  It should either check the mount type and skip caches, or make arrangements to handle those cases.

2025-01-22 22:06 UTC, nalind commented on imagebuildah/util.go
> +
The new types and functions don't need to be exported.

2025-01-22 22:07 UTC, nalind commented on imagebuildah/util.go
> +		tarWriter.Close()
Duplicate call.
```suggestion
```

2025-01-22 22:11 UTC, nalind commented on imagebuildah/util_test.go
> +	tempDir, err := os.MkdirTemp("", "testdir")
Use a value returned by `t.TempDir()`.  It was introduced in Go 1.15, and you don't need to clean it up.

2025-01-22 22:18 UTC, nalind commented on tests/bud.bats
> +  # on third run since we have added new file `anotherfile` so cache must burst.
Update this comment.

2025-01-22 22:23 UTC, nalind commented on imagebuildah/util.go
> +		header, err := tar.FileInfoHeader(info, "")
This second parameter is still incorrect for cases where, I think, `info.Mode().Type()` is `fs.ModeSymlink`.  The integration test should include at least one symbolic link in the test directory, which is overwritten using `ln -sf` between invocations.

2025-01-22 22:27 UTC, nalind commented on imagebuildah/stage_executor.go
> +			if mountOptionFrom != "" {
This value, along with `mountOptionSource`, isn't being reset between loop iterations.

2025-01-23 18:35 UTC, flouthoc commented on imagebuildah/stage_executor.go
> +			if mountOptionFrom != "" {
Done near loop start.

2025-01-23 20:23 UTC, nalind requested changes
Looking better, but the arg parsing still has a potential crasher in it.

2025-01-23 20:23 UTC, nalind commented on imagebuildah/util_test.go
> +	}
We use the `github.com/stretchr/testify/assert` package for a lot of these.
```suggestion
	assert.Equal(t, expectedChecksum, checksum, "didn't get expected checksum over a sample directory")
```

2025-01-23 23:45 UTC, flouthoc commented
@nalind Could you PTAL again.

2025-01-24 16:10 UTC, nalind commented
/lgtm

2025-01-24 17:00 UTC, flouthoc commented
@rhatdan @containers/build-maintainers PTAL

2025-01-25 11:31 UTC, rhatdan commented
/approve

2025-01-25 11:35 UTC, merged