Makefile: list sources via `find` conditionally
containers/buildah pull request #5807
Opened 2024-10-31 01:49 UTC by danishprakash

Taken directly from podman's Makefile. The current list doesn't list vendor sources and therefore if you need to build and test your changes to vendor/ for testing a backport or anything else, it's required to modify the Makefile before attempting to do so.

/kind other

Signed-off-by: Danish Prakash <contact@danishpraka.sh>

2024-10-31 01:51 UTC, danishprakash commented
@nalind I noticed you've added certain sources over time, so if there's a reason to selectively list sources that I'm not aware of, I can also only add `vendor/*`, that should also be good enough.

2024-10-31 14:00 UTC, nalind commented
I hadn't considered that modifying files under `vendor` was a common enough case that the Makefile needed to account for it.  Trying to add everything under `vendor` into the current SOURCES list seems like something that the bot that keeps our dependencies up to date would trip over, so if this doesn't slow down `make`, then I guess the thing to do is remove the part of the smoke test that fails.

2024-11-02 08:10 UTC, danishprakash commented
> I hadn't considered that modifying files under vendor was a common enough case that the Makefile needed to account for it.

I mean I use it quite often w/ podman when testing c/* changes and it's come in quite handy.

---

> then I guess the thing to do is remove the part of the smoke test that fails.

We were validating the sources _because_ we were listing them manually, I guess moving to a finder cmd, I don't see the need for a validation anymore, wdyt? 

Do we have benchmarks to test if there's a performance degradation? I can think of vendor bumps as an additional trigger for rebuilds, can't think of anything major that should have an impact.

2024-11-04 10:39 UTC, Luap99 reviewed
If a go file changed we should rebuild, in vendor/ or not. Because if I do a dependency bump locally via gp.mod then make buildah currently doesn't rebuild so this is clearly broken.  As such I think this here is the right idea.

I don't see any advantage of listing all the packages here so the find seems much better to me. Even if it would pick something up that does not need to trigger a rebuild all the time go rebuilds are fast anyway so I would not be concerned about speed.

2024-11-04 10:39 UTC, Luap99 commented on Makefile
> +# newer than our target (bin/podman{,-remote}), a rebuild is
the bind/podman comment is not accurate here

2024-11-07 12:59 UTC, rhatdan commented
LGTM

2024-11-07 14:18 UTC, nalind commented
/approve

2024-11-09 00:21 UTC, kolyshkin requested changes
You should probably also remove *.go files from some of the targets that use `$(SOURCES). For example:

```make
bin/buildah: $(SOURCES) cmd/buildah/*.go internal/mkcw/embed/entrypoint_amd64.gz
````

Here `cmd/buildah/*.go` is becoming redundant.

2024-11-20 23:32 UTC, merged